/*global systemDictionary:true */
"use strict";

systemDictionary = {
  "webuntis adapter settings": {
    en: "Adapter settings for webuntis",
    de: "Adaptereinstellungen für webuntis",
    ru: "Настройки адаптера для webuntis",
    pt: "Configurações do adaptador para webuntis",
    nl: "Adapterinstellingen voor webuntis",
    fr: "Paramètres d'adaptateur pour webuntis",
    it: "Impostazioni dell'adattatore per webuntis",
    es: "Ajustes del adaptador para webuntis",
    pl: "Ustawienia adaptera dla webuntis",
    "zh-cn": "webuntis的适配器设置",
  },
  "Login method": {
    en: "Login method",
    de: "Anmeldemethode",
    ru: "Логин метод",
    pt: "Método de login",
    nl: "Login methode",
    fr: "Méthode d ' identification",
    it: "Metodo di login",
    es: "Método de inicio",
    pl: "Metoda loginowa",
    "zh-cn": "逻辑方法",
  },
  anonymous: {
    en: "anonymous",
    de: "anonym",
    ru: "анонимный",
    pt: "anônimo",
    nl: "anoniem",
    fr: "anonyme",
    it: "anonimo",
    es: "anónimo",
    pl: "anonimowy",
    "zh-cn": "匿名的",
  },

  "Class name - leave blank, if anonymous login is not supported": {
    en: "Class name - leave blank, if anonymous login is not supported",
    de: "Klassenname - leer lassen, wenn anonyme Anmeldung nicht unterstützt wird",
    ru: "Название класса - оставьте пустое, если анонимный логин не поддерживается",
    pt: "Nome da classe - deixar em branco, se o login anônimo não for suportado",
    nl: "Klassenaam, laat niets achter, als anonieme login niet ondersteund is",
    fr: "Nom de la classe - laisser vierge, si un login anonyme n'est pas pris en charge",
    it: "Nome di classe - lasciare vuoto, se il login anonimo non è supportato",
    es: "Nombre de clase - dejar en blanco, si el acceso anónimo no es compatible",
    pl: "Nazwa klasy – pusta, jeśli anonimowa logina nie jest wspierana",
    "zh-cn": "姓名:如果匿名的逻辑得不到支持,便可离开空白。",
  },
  Username: {
    en: "Username",
    de: "Nutzername",
    ru: "Имя пользователя",
    pt: "Nome do usuário",
    nl: "gebruikersnaam",
    fr: "Nom d'utilisateur",
    it: "Nome utente",
    es: "Nombre de usuario",
    pl: "Nazwa użytkownika",
    "zh-cn": "用户名",
  },
  "Password/Secret": {
    en: "Password/Secret",
    de: "Passwort/Secret",
    ru: "Пароль/Secret",
    pt: "Senha/Secret",
    nl: "Wachtwoord/Secret",
    fr: "Mot de passe/Secret",
    it: "Parola d'ordine/Secret",
    es: "Contraseña/Secret",
    pl: "Hasło/Secret",
    "zh-cn": "密码/Secret",
  },
  "School settings": {
    en: "School settings",
    de: "Schuleinstellungen",
    ru: "Настройки школы",
    pt: "Configurações da escola",
    nl: "Schoolinstellingen",
    fr: "Paramètres de l'école",
    it: "Impostazioni scolastiche",
    es: "entornos escolares",
    pl: "Ustawienia szkolne",
    "zh-cn": "学校设置",
  },
  "School secret": {
    en: "School secret",
    de: "Schulgeheimnis",
    ru: "Школьный секрет",
    pt: "Segredo da escola",
    nl: "School geheim",
    fr: "Le secret de l'école",
    it: "Segreto della scuola",
    es: "secreto de la escuela",
    pl: "Sekret szkolny",
    "zh-cn": "学校秘密",
  },
  "School base url": {
    en: "School base url",
    de: "Basis-URL der Schule",
    ru: "Базовый URL школы",
    pt: "URL base da escola",
    nl: "Basis-URL van school",
    fr: "URL de base de l'école",
    it: "URL base della scuola",
    es: "URL base de la escuela",
    pl: "URL bazy szkolnej",
    "zh-cn": "学校基地网址",
  },
};
